----------------
--  PRIMARY KEYS
----------------

-- FUN

ALTER TABLE FUN_FUNCTION ADD CONSTRAINT PK_FUN_FUNCTION PRIMARY KEY (ID);
ALTER TABLE FUN_TRANSITION_TABLE ADD CONSTRAINT PK_FUN_TRANSITION_TABLE PRIMARY KEY (ID);
ALTER TABLE FUN_EXPRESSION ADD CONSTRAINT PK_FUN_EXPRESSION PRIMARY KEY (ID);
ALTER TABLE FUN_RANDOM_DISTRIBUTION ADD CONSTRAINT PK_FUN_RANDOM_DISTRIBUTION PRIMARY KEY (ID);

-- NET

ALTER TABLE NET_TOPOLOGY ADD CONSTRAINT PK_NET_TOPOLOGY PRIMARY KEY (ID);
ALTER TABLE NET_TEMPLATE_TOPOLOGY ADD CONSTRAINT PK_NET_TEMPLATE_TOPOLOGY PRIMARY KEY (TOPOLOGY_ID);
ALTER TABLE NET_SPATIAL_TOPOLOGY ADD CONSTRAINT PK_NET_SPATIAL_TOPOLOGY PRIMARY KEY (TOPOLOGY_ID);
ALTER TABLE NET_SPATIAL_NEIGHBORHOOD ADD CONSTRAINT PK_NET_SPATIAL_NEIGHBORHOOD PRIMARY KEY (ID);
ALTER TABLE NET_SPATIAL_NEIGHBOR ADD CONSTRAINT PK_NET_SPATIAL_NEIGHBOR PRIMARY KEY (ID);
ALTER TABLE NET_WEIGHT_SETTING ADD CONSTRAINT PK_NET_WEIGHT_SETTING PRIMARY KEY (ID);
ALTER TABLE NET_NETWORK ADD CONSTRAINT PK_NET_NETWORK PRIMARY KEY (ID);
ALTER TABLE NET_FUNCTION ADD CONSTRAINT PK_NET_FUNCTION PRIMARY KEY (ID);
ALTER TABLE NET_ACTION_SERIES ADD CONSTRAINT PK_NET_ACTION_SERIES PRIMARY KEY (ID);
ALTER TABLE NET_ACTION ADD CONSTRAINT PK_NET_ACTION PRIMARY KEY (ID);

ALTER TABLE NET_EVALUATION ADD CONSTRAINT PK_NET_EVALUATION PRIMARY KEY (ID);
ALTER TABLE NET_PERFORMANCE ADD CONSTRAINT PK_NET_PERFORMANCE PRIMARY KEY (ID);
ALTER TABLE NET_EVALUATION_ITEM ADD CONSTRAINT PK_NET_EVALUATION_ITEM PRIMARY KEY (ID);
ALTER TABLE NET_EVALUATION_VAR ADD CONSTRAINT PK_NET_EVALUATION_VAR PRIMARY KEY (ID);

ALTER TABLE NET_DERRIDA ADD CONSTRAINT PK_NET_DERRIDA PRIMARY KEY (ID);
ALTER TABLE NET_DAMAGE_SPREADING ADD CONSTRAINT PK_NET_DAMAGE_SPREADING PRIMARY KEY (ID);

-- AC

ALTER TABLE AC_ARTIFICIAL_CHEMISTRY ADD CONSTRAINT PK_AC_ARTIFICIAL_CHEMISTRY PRIMARY KEY (ID);
ALTER TABLE AC_SPECIES ADD CONSTRAINT PK_AC_SPECIES PRIMARY KEY (ID);
ALTER TABLE AC_SPECIES_SET ADD CONSTRAINT PK_AC_SPECIES_SET PRIMARY KEY (ID);
ALTER TABLE AC_PARAMETER ADD CONSTRAINT PK_AC_PARAMETER PRIMARY KEY (ID);
ALTER TABLE AC_PARAMETER_SET ADD CONSTRAINT PK_AC_PARAMETER_SET PRIMARY KEY (ID);
ALTER TABLE AC_REACTION ADD CONSTRAINT PK_AC_REACTION PRIMARY KEY (ID);
ALTER TABLE AC_SPECIES_REACTION_ASSOCIATION ADD CONSTRAINT PK_AC_SPECIES_REACTION_ASSOCIATION PRIMARY KEY (ID);
ALTER TABLE AC_REACTION_SET ADD CONSTRAINT PK_AC_REACTION_SET PRIMARY KEY (ID);
ALTER TABLE AC_REACTION_GROUP ADD CONSTRAINT PK_AC_REACTION_GROUP PRIMARY KEY (ID);
ALTER TABLE AC_COMPARTMENT ADD CONSTRAINT PK_AC_COMPARTMENT PRIMARY KEY (ID);
ALTER TABLE AC_SUB_COMPARTMENT_ASSOCIATION ADD CONSTRAINT PK_AC_SUB_COMPARTMENT_ASSOCIATION PRIMARY KEY (ID);
ALTER TABLE AC_COMPARTMENT_CHANNEL ADD CONSTRAINT PK_AC_COMPARTMENT_CHANNEL PRIMARY KEY (ID);
ALTER TABLE AC_COMPARTMENT_CHANNEL_GROUP ADD CONSTRAINT PK_AC_COMPARTMENT_CHANNEL_GROUP PRIMARY KEY (ID);

ALTER TABLE AC_SPECIES_ACTION ADD CONSTRAINT PK_AC_SPECIES_ACTION PRIMARY KEY (ID);
ALTER TABLE AC_ACTION ADD CONSTRAINT PK_AC_ACTION PRIMARY KEY (ID);
ALTER TABLE AC_ACTION_SERIES ADD CONSTRAINT PK_AC_ACTION_SERIES PRIMARY KEY (ID);
ALTER TABLE AC_ACTION_VAR ADD CONSTRAINT PK_AC_ACTION_VAR PRIMARY KEY (ID);
ALTER TABLE AC_CACHE_WRITE ADD CONSTRAINT PK_AC_CACHE_WRITE PRIMARY KEY (ID);

ALTER TABLE AC_EVALUATED_SPECIES_ACTION ADD CONSTRAINT PK_AC_EVALUATED_SPECIES_ACTION PRIMARY KEY (ID);
ALTER TABLE AC_EVALUATED_ACTION ADD CONSTRAINT PK_AC_EVALUATED_ACTION PRIMARY KEY (ID);
ALTER TABLE AC_EVALUATED_ACTION_SERIES ADD CONSTRAINT PK_AC_EVALUATED_ACTION_SERIES PRIMARY KEY (ID);
ALTER TABLE AC_RUN ADD CONSTRAINT PK_AC_RUN PRIMARY KEY (ID);
ALTER TABLE AC_SPECIES_HISTORY ADD CONSTRAINT PK_AC_SPECIES_HISTORY PRIMARY KEY (ID);

ALTER TABLE AC_TRANSLATION_ITEM ADD CONSTRAINT PK_AC_TRANSLATION_ITEM PRIMARY KEY (ID);
ALTER TABLE AC_RANGE_TRANSLATION ADD CONSTRAINT PK_AC_RANGE_TRANSLATION PRIMARY KEY (ID);
ALTER TABLE AC_TRANSLATION_SERIES ADD CONSTRAINT PK_AC_TRANSLATION_SERIES PRIMARY KEY (ID);
ALTER TABLE AC_TRANSLATED_RUN ADD CONSTRAINT PK_AC_TRANSLATED_RUN PRIMARY KEY (ID);
ALTER TABLE AC_TRANSLATION_ITEM_HISTORY ADD CONSTRAINT PK_AC_TRANSLATION_ITEM_HISTORY PRIMARY KEY (ID);
ALTER TABLE AC_TRANSLATION_VAR ADD CONSTRAINT PK_AC_TRANSLATION_VAR PRIMARY KEY (ID);

ALTER TABLE AC_EVALUATED_RUN ADD CONSTRAINT PK_AC_EVALUATED_RUN PRIMARY KEY (ID);
ALTER TABLE AC_EVALUATION ADD CONSTRAINT PK_AC_EVALUATION PRIMARY KEY (ID);
ALTER TABLE AC_EVALUATED_PERFORMANCE ADD CONSTRAINT PK_AC_EVALUATED_PERFORMANCE PRIMARY KEY (ID);
ALTER TABLE AC_RATE_CONSTANT_TYPE_BOUND ADD CONSTRAINT PK_AC_RATE_CONSTANT_TYPE_BOUND PRIMARY KEY (ID);
ALTER TABLE AC_PERFORMANCE_RATE_CONSTANT_TYPE_BOUND_MAPPING ADD CONSTRAINT PK_AC_PERFORMANCE_RATE_CONSTANT_TYPE_BOUND_MAPPING PRIMARY KEY (RANDOM_RATE_PERFORMANCE_ID, RATE_CONSTANT_TYPE_BOUND_ID);

ALTER TABLE AC_ARTIFICIAL_CHEMISTRY_SPEC ADD CONSTRAINT PK_AC_ARTIFICIAL_CHEMISTRY_SPEC PRIMARY KEY (ID);
ALTER TABLE AC_SIMULATION_CONFIG ADD CONSTRAINT PK_AC_SIMULATION_CONFIG PRIMARY KEY (ID);
ALTER TABLE AC_ARTIFICIAL_CHEMISTRY_SPEC_BOUND ADD CONSTRAINT PK_AC_ARTIFICIAL_CHEMISTRY_SPEC_BOUND PRIMARY KEY (ID);

-- UM

ALTER TABLE UM_USER ADD CONSTRAINT PK_UM_USER PRIMARY KEY (ID);
ALTER TABLE UM_ROLE ADD CONSTRAINT PK_UM_ROLE PRIMARY KEY (ID);
ALTER TABLE UM_USER_ROLE_MAPPING ADD CONSTRAINT PK_UM_USER_ROLE_MAPPING PRIMARY KEY (USER_ID, ROLE_ID);

-- EVO

ALTER TABLE EVO_GA_SETTING ADD CONSTRAINT PK_EVO_GA_SETTING PRIMARY KEY (ID);
ALTER TABLE EVO_AC_TASK ADD CONSTRAINT PK_EVO_AC_TASK PRIMARY KEY (ID);
ALTER TABLE EVO_AC_TASK_ACTION_SERIES_MAPPING ADD CONSTRAINT PK_EVO_AC_TASK_ACTION_SERIES_MAPPING PRIMARY KEY (ID);
ALTER TABLE EVO_AC_TASK_RATE_CONSTANT_TYPE_BOUND_MAPPING ADD CONSTRAINT PK_EVO_AC_TASK_RATE_CONSTANT_TYPE_BOUND_MAPPING PRIMARY KEY (EVO_AC_TASK_ID, RATE_CONSTANT_TYPE_BOUND_ID);
ALTER TABLE EVO_AC_TASK_REACTION_MAPPING ADD CONSTRAINT PK_EVO_AC_TASK_REACTION_MAPPING PRIMARY KEY (EVO_AC_TASK_ID, REACTION_ID);
ALTER TABLE EVO_AC_TASK_REACTION_GROUP_MAPPING ADD CONSTRAINT PK_EVO_AC_TASK_REACTION_GROUP_MAPPING PRIMARY KEY (EVO_AC_TASK_ID, REACTION_GROUP_ID);

ALTER TABLE EVO_AC_SPECIES_ASSIGNMENT_BOUND ADD CONSTRAINT PK_EVO_AC_SPECIES_ASSIGNMENT_BOUND PRIMARY KEY (ID);
ALTER TABLE EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_BOUND ADD CONSTRAINT PK_EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_BOUND PRIMARY KEY (ID);
ALTER TABLE EVO_AC_SPECIES_ASSIGNMENT_MAPPING ADD CONSTRAINT PK_EVO_AC_SPECIES_ASSIGNMENT_MAPPING PRIMARY KEY (EVO_AC_SPECIES_BOUND_ID, SPECIES_ASSIGNMENT_ID);
ALTER TABLE EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_MAPPING ADD CONSTRAINT PK_EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_MAPPING PRIMARY KEY (EVO_AC_VARIABLE_BOUND_ID, VARIABLE_ASSIGNMENT_ID);

ALTER TABLE EVO_RUN ADD CONSTRAINT PK_EVO_RUN PRIMARY KEY (ID);
ALTER TABLE EVO_POPULATION ADD CONSTRAINT PK_EVO_POPULATION PRIMARY KEY (ID);
ALTER TABLE EVO_CHROMOSOME ADD CONSTRAINT PK_EVO_CHROMOSOME PRIMARY KEY (ID);

-- DYN

ALTER TABLE DYN_STATS ADD CONSTRAINT PK_DYN_STATS PRIMARY KEY (ID); 
ALTER TABLE DYN_STATS_SEQ ADD CONSTRAINT PK_DYN_STATS_SEQ PRIMARY KEY (ID); 
ALTER TABLE DYN_SINGLE_ANALYSIS_SPEC ADD CONSTRAINT PK_DYN_SINGLE_ANALYSIS_SPEC PRIMARY KEY (ID);
ALTER TABLE DYN_MULTI_ANALYSIS_SPEC ADD CONSTRAINT PK_DYN_MULTI_ANALYSIS_SPEC PRIMARY KEY (ID);
ALTER TABLE DYN_SINGLE_ANALYSIS_RESULT ADD CONSTRAINT PK_DYN_SINGLE_ANALYSIS_RESULT PRIMARY KEY (ID);
ALTER TABLE DYN_MULTI_ANALYSIS_RESULT ADD CONSTRAINT PK_DYN_MULTI_ANALYSIS_RESULT PRIMARY KEY (ID);

-- TASK

ALTER TABLE TASK ADD CONSTRAINT PK_TASK PRIMARY KEY (ID);
ALTER TABLE TASK_EVO_RUN ADD CONSTRAINT PK_EVO_RUN_DEF PRIMARY KEY (TASK_ID);

---------------
--  UNIQUE KEYS
---------------

-- NET

-- AC

ALTER TABLE AC_SPECIES ADD CONSTRAINT UK_AC_SPECIES UNIQUE (label, species_set_id);
ALTER TABLE AC_SPECIES ADD CONSTRAINT UK_AC_SPECIES_2 UNIQUE (variable_index, species_set_id);

ALTER TABLE AC_PARAMETER ADD CONSTRAINT UK_AC_PARAMETER UNIQUE (label, parameter_set_id);
ALTER TABLE AC_PARAMETER ADD CONSTRAINT UK_AC_PARAMETER_2 UNIQUE (variable_index, parameter_set_id);

ALTER TABLE AC_REACTION ADD CONSTRAINT UK_AC_REACTION UNIQUE (label, reaction_set_id);

--ALTER TABLE AC_SPECIES_REACTION_ASSOCIATION ADD CONSTRAINT UK_AC_SPECIES_REACTION_ASSOCIATION UNIQUE (species_id, reaction_id, assoc_type);

ALTER TABLE AC_SPECIES_ACTION ADD CONSTRAINT UK_AC_SPECIES_ACTION UNIQUE (species_id, action_id);

ALTER TABLE AC_ACTION ADD CONSTRAINT UK_AC_ACTION UNIQUE (start_time, action_series_id);

ALTER TABLE AC_ACTION_VAR ADD CONSTRAINT UK_AC_ACTION_VAR UNIQUE (label, action_series_id);
ALTER TABLE AC_ACTION_VAR ADD CONSTRAINT UK_AC_ACTION_VAR_2 UNIQUE (variable_index, action_series_id);

ALTER TABLE AC_EVALUATED_SPECIES_ACTION ADD CONSTRAINT UK_AC_EVALUATED_SPECIES_ACTION UNIQUE (species_action_id, evaluated_action_id);

ALTER TABLE AC_SPECIES_HISTORY ADD CONSTRAINT UK_AC_SPECIES_HISTORY UNIQUE (species_id, run_id);

ALTER TABLE AC_TRANSLATION_ITEM ADD CONSTRAINT UK_AC_TRANSLATION_ITEM UNIQUE (translation_var_id, translation_id);

ALTER TABLE AC_TRANSLATION_ITEM_HISTORY ADD CONSTRAINT UK_AC_TRANSLATION_ITEM_HISTORY UNIQUE (translation_var_id, translated_run_id);

ALTER TABLE AC_TRANSLATION_VAR ADD CONSTRAINT UK_AC_TRANSLATION_VAR UNIQUE (label, translation_series_id);
ALTER TABLE AC_TRANSLATION_VAR ADD CONSTRAINT UK_AC_TRANSLATION_VAR_2 UNIQUE (variable_index, translation_series_id);

-- UM

ALTER TABLE UM_USER ADD CONSTRAINT UK_UM_USER_1 UNIQUE (username);
ALTER TABLE UM_USER ADD CONSTRAINT UK_UM_USER_2 UNIQUE (email);
ALTER TABLE UM_ROLE ADD CONSTRAINT UK_UM_ROLE_1 UNIQUE (name);
ALTER TABLE UM_USER_ROLE_MAPPING ADD CONSTRAINT UK_UM_USER_ROLE_MAPPING UNIQUE (user_id, role_id);

---------------
-- FOREIGN KEYS
---------------

-- FUN

ALTER TABLE FUN_FUNCTION ADD CONSTRAINT FK_FUN_FUNCTION_PARENT FOREIGN KEY (parent_id) REFERENCES FUN_FUNCTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE FUN_TRANSITION_TABLE ADD CONSTRAINT FK_FUN_TRANSITION_TABLE_FUN FOREIGN KEY (id) REFERENCES FUN_FUNCTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE FUN_EXPRESSION ADD CONSTRAINT FK_FUN_EXPRESSION_FUN FOREIGN KEY (id) REFERENCES FUN_FUNCTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- NET

ALTER TABLE NET_LAYER_TOPOLOGY_MAPPING ADD CONSTRAINT FK_NET_LAYER_TOPOLOGY_MAPPING_PARENT FOREIGN KEY (parent_id) REFERENCES NET_TOPOLOGY (id) ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE NET_LAYER_TOPOLOGY_MAPPING ADD CONSTRAINT FK_NET_LAYER_TOPOLOGY_MAPPING_LAYER FOREIGN KEY (layer_id) REFERENCES NET_TOPOLOGY (id) ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE NET_TOPOLOGY ADD CONSTRAINT FK_NET_TOPOLOGY_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_TEMPLATE_TOPOLOGY ADD CONSTRAINT FK_NET_TEMPLATE_TOPOLOGY_BASE FOREIGN KEY (topology_id) REFERENCES NET_TOPOLOGY (id) ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE NET_SPATIAL_TOPOLOGY ADD CONSTRAINT FK_NET_SPATIAL_TOPOLOGY_BASE FOREIGN KEY (topology_id) REFERENCES NET_TOPOLOGY (id) ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE NET_SPATIAL_TOPOLOGY ADD CONSTRAINT FK_NET_SPATIAL_TOPOLOGY_NEIGHBORHOOD FOREIGN KEY (neighborhood_id) REFERENCES NET_SPATIAL_NEIGHBORHOOD (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE NET_WEIGHT_SETTING ADD CONSTRAINT FK_NET_WEIGHT_SETTING_PARENT FOREIGN KEY (parent_id) REFERENCES NET_WEIGHT_SETTING (id) ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE NET_WEIGHT_SETTING ADD CONSTRAINT FK_NET_WEIGHT_SETTING_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_WEIGHT_SETTING ADD CONSTRAINT FK_NET_WEIGHT_SETTING_RANDOM_DISTRIBUTION FOREIGN KEY (random_distribution_id) REFERENCES FUN_RANDOM_DISTRIBUTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE NET_FUNCTION ADD CONSTRAINT FK_NET_FUNCTION_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_FUNCTION ADD CONSTRAINT FK_NET_FUNCTION_PARENT FOREIGN KEY (parent_id) REFERENCES NET_FUNCTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_FUNCTION ADD CONSTRAINT FK_NET_FUNCTION_FUNCTION FOREIGN KEY (function_id) REFERENCES FUN_FUNCTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE NET_NETWORK ADD CONSTRAINT FK_NET_NETWORK_TOPOLOGY FOREIGN KEY (topology_id) REFERENCES NET_TOPOLOGY (id) ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE NET_NETWORK ADD CONSTRAINT FK_NET_NETWORK_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_NETWORK ADD CONSTRAINT FK_NET_NETWORK_WEIGHT_SETTING FOREIGN KEY (weight_setting_id) REFERENCES NET_WEIGHT_SETTING (id) ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE NET_NETWORK ADD CONSTRAINT FK_NET_NETWORK_FUNCTION FOREIGN KEY (function_id) REFERENCES NET_FUNCTION (id) ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE NET_SPATIAL_NEIGHBORHOOD ADD CONSTRAINT FK_NET_SPATIAL_NEIGHBORHOOD_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_SPATIAL_NEIGHBOR ADD CONSTRAINT FK_NET_SPATIAL_NEIGHBOR_PARENT FOREIGN KEY (parent_id) REFERENCES NET_SPATIAL_NEIGHBORHOOD (id) ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE NET_ACTION_SERIES ADD CONSTRAINT FK_NET_ACTION_SERIES_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_ACTION ADD CONSTRAINT FK_NET_ACTION_SERIES FOREIGN KEY (action_series_id) REFERENCES NET_ACTION_SERIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_ACTION ADD CONSTRAINT FK_NET_ACTION_RANDOM_DISTRIBUTION FOREIGN KEY (state_distribution_id) REFERENCES FUN_RANDOM_DISTRIBUTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE NET_EVALUATION ADD CONSTRAINT FK_NET_EVALUATION_FUNCTION FOREIGN KEY (evaluation_fun_id) REFERENCES FUN_FUNCTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_EVALUATION ADD CONSTRAINT FK_NET_EVALUATION_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_EVALUATION_ITEM ADD CONSTRAINT FK_NET_EVALUATION_ITEM_EVALUATION FOREIGN KEY (evaluation_id) REFERENCES NET_EVALUATION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_EVALUATION_ITEM ADD CONSTRAINT FK_NET_EVALUATION_ITEM_VAR FOREIGN KEY (evaluation_var_id) REFERENCES NET_EVALUATION_VAR (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_EVALUATION_ITEM ADD CONSTRAINT FK_NET_EVALUATION_ITEM_FUNCTION FOREIGN KEY (eval_fun_id) REFERENCES FUN_FUNCTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_EVALUATION_VAR ADD CONSTRAINT FK_NET_EVALUATION_VAR_EVALUATION FOREIGN KEY (evaluation_id) REFERENCES NET_EVALUATION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE NET_PERFORMANCE ADD CONSTRAINT FK_NET_PERFORMANCE_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_PERFORMANCE ADD CONSTRAINT FK_NET_PERFORMANCE_ACTION_SERIES FOREIGN KEY (action_series_id) REFERENCES NET_ACTION_SERIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_PERFORMANCE ADD CONSTRAINT FK_NET_PERFORMANCE_NETWORK FOREIGN KEY (network_id) REFERENCES NET_NETWORK (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_PERFORMANCE ADD CONSTRAINT FK_NET_PERFORMANCE_EVALUATION FOREIGN KEY (evaluation_id) REFERENCES NET_EVALUATION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_PERFORMANCE ADD CONSTRAINT FK_NET_PERFORMANCE_STATS FOREIGN KEY (result_stats_id) REFERENCES DYN_STATS (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_PERFORMANCE ADD CONSTRAINT FK_NET_PERFORMANCE_STATS_SEQ FOREIGN KEY (result_stats_seq_id) REFERENCES DYN_STATS_SEQ (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE NET_DERRIDA ADD CONSTRAINT FK_NET_DERRIDA_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_DERRIDA ADD CONSTRAINT FK_NET_DERRIDA_NETWORK FOREIGN KEY (network_id) REFERENCES NET_NETWORK (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_DERRIDA ADD CONSTRAINT FK_NET_DERRIDA_STATS_SEQ FOREIGN KEY (result_stats_seq_id) REFERENCES DYN_STATS_SEQ (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE NET_DAMAGE_SPREADING ADD CONSTRAINT FK_NET_DAMAGE_SPREADING_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_DAMAGE_SPREADING ADD CONSTRAINT FK_NET_DAMAGE_SPREADING_NETWORK FOREIGN KEY (network_id) REFERENCES NET_NETWORK (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE NET_DAMAGE_SPREADING ADD CONSTRAINT FK_NET_DAMAGE_SPREADING_STATS_SEQ FOREIGN KEY (result_stats_seq_id) REFERENCES DYN_STATS_SEQ (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- AC

ALTER TABLE AC_ARTIFICIAL_CHEMISTRY ADD CONSTRAINT FK_AC_ARTIFICIAL_CHEMISTRY_SKIN_COMPARTMENT FOREIGN KEY (skin_compartment_id) REFERENCES AC_COMPARTMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_ARTIFICIAL_CHEMISTRY ADD CONSTRAINT FK_AC_ARTIFICIAL_CHEMISTRY_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_ARTIFICIAL_CHEMISTRY ADD CONSTRAINT FK_AC_ARTIFICIAL_CHEMISTRY_SPEC FOREIGN KEY (generated_by_spec_id) REFERENCES AC_ARTIFICIAL_CHEMISTRY_SPEC (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_ARTIFICIAL_CHEMISTRY ADD CONSTRAINT FK_AC_ARTIFICIAL_CHEMISTRY_CONFIG FOREIGN KEY (simulation_config_id) REFERENCES AC_SIMULATION_CONFIG (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_SPECIES ADD CONSTRAINT FK_AC_SPECIES_SET FOREIGN KEY (species_set_id) REFERENCES AC_SPECIES_SET (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_SPECIES_SET ADD CONSTRAINT FK_AC_SPECIES_SET_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_SPECIES_SET ADD CONSTRAINT FK_AC_SPECIES_SET_PARENT FOREIGN KEY (parent_set) REFERENCES AC_SPECIES_SET (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_PARAMETER ADD CONSTRAINT FK_AC_PARAMETER_SET FOREIGN KEY (parameter_set_id) REFERENCES AC_PARAMETER_SET (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_PARAMETER ADD CONSTRAINT FK_AC_PARAMETER_FUN FOREIGN KEY (evol_function_id) REFERENCES FUN_FUNCTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_PARAMETER_SET ADD CONSTRAINT FK_AC_PARAMETER_SET_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_REACTION ADD CONSTRAINT FK_AC_REACTION_SET FOREIGN KEY (reaction_set_id) REFERENCES AC_REACTION_SET (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_REACTION ADD CONSTRAINT FK_AC_REACTION_FORWARD_RATE_FUN FOREIGN KEY (forward_rate_function_id) REFERENCES FUN_FUNCTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_REACTION ADD CONSTRAINT FK_AC_REACTION_REVERSE_RATE_FUN FOREIGN KEY (reverse_rate_function_id) REFERENCES FUN_FUNCTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_REACTION ADD CONSTRAINT FK_AC_REACTION_GROUP FOREIGN KEY (reaction_group_id) REFERENCES AC_REACTION_GROUP(id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_REACTION_GROUP ADD CONSTRAINT FK_AC_REACTION_GROUP_SET FOREIGN KEY (reaction_set_id) REFERENCES AC_REACTION_SET(id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_SPECIES_REACTION_ASSOCIATION ADD CONSTRAINT FK_AC_SPECIES_REACTION_ASSOC_SPECIES FOREIGN KEY (species_id) REFERENCES AC_SPECIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_SPECIES_REACTION_ASSOCIATION ADD CONSTRAINT FK_AC_SPECIES_REACTION_ASSOC_REACTION FOREIGN KEY (reaction_id) REFERENCES AC_REACTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_REACTION_SET ADD CONSTRAINT FK_AC_REACTION_SET_SPECIES_SET FOREIGN KEY (species_set_id) REFERENCES AC_SPECIES_SET (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_REACTION_SET ADD CONSTRAINT FK_AC_REACTION_SET_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_COMPARTMENT ADD CONSTRAINT FK_AC_COMPARTMENT_REACTION_SET FOREIGN KEY (reaction_set_id) REFERENCES AC_REACTION_SET (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_COMPARTMENT ADD CONSTRAINT FK_AC_COMPARTMENT_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_SUB_COMPARTMENT_ASSOCIATION ADD CONSTRAINT FK_AC_SUB_COMPARTMENT_ASSOCIATION_PARENT FOREIGN KEY (parent_id) REFERENCES AC_COMPARTMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_SUB_COMPARTMENT_ASSOCIATION ADD CONSTRAINT FK_AC_SUB_COMPARTMENT_ASSOCIATION_SUB FOREIGN KEY (sub_id) REFERENCES AC_COMPARTMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_COMPARTMENT_CHANNEL ADD CONSTRAINT FK_AC_COMPARTMENT_CHANNEL_COMPARTMENT FOREIGN KEY (compartment_id) REFERENCES AC_COMPARTMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_COMPARTMENT_CHANNEL ADD CONSTRAINT FK_AC_COMPARTMENT_CHANNEL_SOURCE FOREIGN KEY (source_species_id) REFERENCES AC_SPECIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_COMPARTMENT_CHANNEL ADD CONSTRAINT FK_AC_COMPARTMENT_CHANNEL_TARGET FOREIGN KEY (target_species_id) REFERENCES AC_SPECIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_COMPARTMENT_CHANNEL_GROUP ADD CONSTRAINT FK_AC_COMPARTMENT_CHANNEL_GROUP_COMPARTMENT FOREIGN KEY (compartment_id) REFERENCES AC_COMPARTMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_COMPARTMENT_CHANNEL_GROUP_MAPPING ADD CONSTRAINT FK_AC_COMPARTMENT_CHANNEL_GROUP_MAPPING_GROUP FOREIGN KEY (group_id) REFERENCES AC_COMPARTMENT_CHANNEL_GROUP (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_COMPARTMENT_CHANNEL_GROUP_MAPPING ADD CONSTRAINT FK_AC_COMPARTMENT_CHANNEL_GROUP_MAPPING_CHANNEL FOREIGN KEY (channel_id) REFERENCES AC_COMPARTMENT_CHANNEL (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_SPECIES_ACTION ADD CONSTRAINT FK_AC_SPECIES_ACTION_ACTION FOREIGN KEY (action_id) REFERENCES AC_ACTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_SPECIES_ACTION ADD CONSTRAINT FK_AC_SPECIES_ACTION_SPECIES FOREIGN KEY (species_id) REFERENCES AC_SPECIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_SPECIES_ACTION ADD CONSTRAINT FK_AC_SPECIES_ACTION_FUN FOREIGN KEY (setting_fun_id) REFERENCES FUN_FUNCTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_ACTION ADD CONSTRAINT FK_AC_ACTION_SERIES FOREIGN KEY (action_series_id) REFERENCES AC_ACTION_SERIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_ACTION_SERIES ADD CONSTRAINT FK_AC_ACTION_SERIES_SPECIES_SET FOREIGN KEY (species_set_id) REFERENCES AC_SPECIES_SET (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_ACTION_SERIES ADD CONSTRAINT FK_AC_ACTION_SERIES_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_ACTION_SERIES ADD CONSTRAINT FK_AC_ACTION_SERIES_PARENT FOREIGN KEY (parent_id) REFERENCES AC_ACTION_SERIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_ACTION_VAR ADD CONSTRAINT FK_AC_ACTION_VAR_SERIES FOREIGN KEY (action_series_id) REFERENCES AC_ACTION_SERIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_CACHE_WRITE ADD CONSTRAINT FK_AC_CACHE_WRITE_ACTION FOREIGN KEY (action_id) REFERENCES AC_ACTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_CACHE_WRITE ADD CONSTRAINT FK_AC_CACHE_WRITE_VAR FOREIGN KEY (variable_id) REFERENCES AC_ACTION_VAR (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_CACHE_WRITE ADD CONSTRAINT FK_AC_CACHE_WRITE_FUN FOREIGN KEY (setting_fun_id) REFERENCES FUN_FUNCTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_ACTION_SERIES_IMMUTABLE_SPECIES_MAPPING ADD CONSTRAINT FK_ACTION_SERIES_IMMUTABLE_SPECIES_MAPPING_ACTION_SERIES FOREIGN KEY (action_series_id) REFERENCES AC_ACTION_SERIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_ACTION_SERIES_IMMUTABLE_SPECIES_MAPPING ADD CONSTRAINT FK_ACTION_SERIES_IMMUTABLE_SPECIES_MAPPING_SPECIES FOREIGN KEY (species_id) REFERENCES AC_SPECIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_EVALUATED_SPECIES_ACTION ADD CONSTRAINT FK_AC_EVALUATED_SPECIES_ACTION_SPECIES_ACTION FOREIGN KEY (species_action_id) REFERENCES AC_SPECIES_ACTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_EVALUATED_SPECIES_ACTION ADD CONSTRAINT FK_AC_EVALUATED_SPECIES_ACTION_EVAL_ACTION FOREIGN KEY (evaluated_action_id) REFERENCES AC_EVALUATED_ACTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_EVALUATED_ACTION ADD CONSTRAINT FK_AC_EVALUATED_ACTION_ACTION FOREIGN KEY (action_id) REFERENCES AC_ACTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_EVALUATED_ACTION ADD CONSTRAINT FK_AC_EVALUATED_ACTION_EVAL_SERIES FOREIGN KEY (evaluated_action_series_id) REFERENCES AC_EVALUATED_ACTION_SERIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_EVALUATED_ACTION_SERIES ADD CONSTRAINT FK_AC_EVALUATED_ACTION_SERIES_SERIES FOREIGN KEY (action_series_id) REFERENCES AC_ACTION_SERIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_EVALUATED_ACTION_SERIES ADD CONSTRAINT FK_AC_EVALUATED_ACTION_SERIES_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_RUN ADD CONSTRAINT FK_AC_RUN_ACTION_SERIES FOREIGN KEY (action_series_id) REFERENCES AC_ACTION_SERIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_RUN ADD CONSTRAINT FK_AC_RUN_AC FOREIGN KEY (ac_id) REFERENCES AC_ARTIFICIAL_CHEMISTRY (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_RUN ADD CONSTRAINT FK_AC_RUN_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_RUN ADD CONSTRAINT FK_AC_RUN_EVAL_ACTION_SERIES FOREIGN KEY (evaluated_action_series_id) REFERENCES AC_EVALUATED_ACTION_SERIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_SPECIES_HISTORY ADD CONSTRAINT FK_AC_SPECIES_HISTORY_RUN FOREIGN KEY (run_id) REFERENCES AC_RUN (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_SPECIES_HISTORY ADD CONSTRAINT FK_AC_SPECIES_HISTORY_SPECIES FOREIGN KEY (species_id) REFERENCES AC_SPECIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_TRANSLATION_ITEM ADD CONSTRAINT FK_AC_TRANSLATION_ITEM_TRANSLATION FOREIGN KEY (translation_id) REFERENCES AC_RANGE_TRANSLATION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_TRANSLATION_ITEM ADD CONSTRAINT FK_AC_TRANSLATION_ITEM_FUN FOREIGN KEY (translation_fun_id) REFERENCES FUN_FUNCTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_TRANSLATION_ITEM ADD CONSTRAINT FK_AC_TRANSLATION_ITEM_VAR FOREIGN KEY (translation_var_id) REFERENCES AC_TRANSLATION_VAR (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_RANGE_TRANSLATION ADD CONSTRAINT FK_AC_RANGE_TRANSLATION_SERIES FOREIGN KEY (translation_series_id) REFERENCES AC_TRANSLATION_SERIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_TRANSLATION_SERIES ADD CONSTRAINT FK_AC_TRANSLATION_SERIES_SPECIES_SET FOREIGN KEY (species_set_id) REFERENCES AC_SPECIES_SET (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_TRANSLATION_SERIES ADD CONSTRAINT FK_AC_TRANSLATION_SERIES_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_TRANSLATED_RUN ADD CONSTRAINT FK_AC_TRANSLATED_RUN_TRANSLATION_SERIES FOREIGN KEY (translation_series_id) REFERENCES AC_TRANSLATION_SERIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_TRANSLATED_RUN ADD CONSTRAINT FK_AC_TRANSLATED_RUN_RUN FOREIGN KEY (run_id) REFERENCES AC_RUN (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_TRANSLATED_RUN ADD CONSTRAINT FK_AC_TRANSLATED_RUN_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_TRANSLATION_ITEM_HISTORY ADD CONSTRAINT FK_AC_TRANSLATION_ITEM_HISTORY_TRANSLATED_RUN FOREIGN KEY (translated_run_id) REFERENCES AC_TRANSLATED_RUN (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_TRANSLATION_ITEM_HISTORY ADD CONSTRAINT FK_AC_TRANSLATION_ITEM_HISTORY_VAR FOREIGN KEY (translation_var_id) REFERENCES AC_TRANSLATION_VAR (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_EVALUATION ADD CONSTRAINT FK_AC_EVALUATION_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_EVALUATION ADD CONSTRAINT FK_AC_EVALUATION_TRANS_SERIES FOREIGN KEY (translation_series_id) REFERENCES AC_TRANSLATION_SERIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_EVALUATION ADD CONSTRAINT FK_AC_EVALUATION_FUN FOREIGN KEY (evaluation_fun_id) REFERENCES FUN_FUNCTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_EVALUATED_RUN ADD CONSTRAINT FK_AC_EVALUATED_RUN_EVALUATION FOREIGN KEY (evaluation_id) REFERENCES AC_EVALUATION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_EVALUATED_RUN ADD CONSTRAINT FK_AC_EVALUATED_RUN_TRANSLATED_RUN FOREIGN KEY (translated_run_id) REFERENCES AC_TRANSLATED_RUN (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_EVALUATED_RUN ADD CONSTRAINT FK_AC_EVALUATED_RUN_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_TRANSLATION_VAR ADD CONSTRAINT FK_AC_TRANSLATION_VAR_SERIES FOREIGN KEY (translation_series_id) REFERENCES AC_TRANSLATION_SERIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- TODO: rename FKs (add FK_ prefix)
ALTER TABLE AC_EVALUATED_PERFORMANCE ADD CONSTRAINT AC_EVALUATED_PERFORMANCE_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_EVALUATED_PERFORMANCE ADD CONSTRAINT AC_EVALUATED_PERFORMANCE_EVALUATION FOREIGN KEY (evaluation_id) REFERENCES AC_EVALUATION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_EVALUATED_PERFORMANCE ADD CONSTRAINT AC_EVALUATED_PERFORMANCE_COMPARTMENT FOREIGN KEY (compartment_id) REFERENCES AC_COMPARTMENT (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_EVALUATED_PERFORMANCE ADD CONSTRAINT AC_EVALUATED_PERFORMANCE_SIM_CONFIG FOREIGN KEY (simulation_config_id) REFERENCES AC_SIMULATION_CONFIG (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_EVALUATED_PERFORMANCE ADD CONSTRAINT AC_EVALUATED_PERFORMANCE_ACTION_SERIES FOREIGN KEY (action_series_id) REFERENCES AC_ACTION_SERIES (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_RATE_CONSTANT_TYPE_BOUND ADD CONSTRAINT AC_RATE_CONSTANT_TYPE_BOUND_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_SIMULATION_CONFIG ADD CONSTRAINT AC_SIMULATION_CONFIG_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE AC_PERFORMANCE_RATE_CONSTANT_TYPE_BOUND_MAPPING ADD CONSTRAINT FK_AC_PERFORMANCE_RATE_CONSTANT_TYPE_BOUND_MAPPING_PERFORMANCE FOREIGN KEY (random_rate_performance_id) REFERENCES AC_EVALUATED_PERFORMANCE (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_PERFORMANCE_RATE_CONSTANT_TYPE_BOUND_MAPPING ADD CONSTRAINT FK_AC_PERFORMANCE_RATE_CONSTANT_TYPE_BOUND_MAPPING_RATE_CONST FOREIGN KEY (rate_constant_type_bound_id) REFERENCES AC_RATE_CONSTANT_TYPE_BOUND (id) ON UPDATE NO ACTION ON DELETE NO ACTION;


ALTER TABLE AC_ARTIFICIAL_CHEMISTRY_SPEC ADD CONSTRAINT FK_ARTIFICIAL_CHEMISTRY_SPEC_RATE_CONSTANT_DIST FOREIGN KEY (rate_constant_distribution_id) REFERENCES FUN_RANDOM_DISTRIBUTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_ARTIFICIAL_CHEMISTRY_SPEC ADD CONSTRAINT FK_ARTIFICIAL_CHEMISTRY_SPEC_INFLUX_RATE_DIST FOREIGN KEY (influx_rate_constant_distribution_id) REFERENCES FUN_RANDOM_DISTRIBUTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_ARTIFICIAL_CHEMISTRY_SPEC ADD CONSTRAINT FK_ARTIFICIAL_CHEMISTRY_SPEC_OUTFLUX_RATE_DIST FOREIGN KEY (outflux_rate_constant_distribution_id) REFERENCES FUN_RANDOM_DISTRIBUTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_ARTIFICIAL_CHEMISTRY_SPEC ADD CONSTRAINT FK_ARTIFICIAL_CHEMISTRY_SPEC_PARTIAL_BINDING_DIST FOREIGN KEY (upper_strand_partial_binding_distribution_id) REFERENCES FUN_RANDOM_DISTRIBUTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_ARTIFICIAL_CHEMISTRY_SPEC ADD CONSTRAINT FK_ARTIFICIAL_CHEMISTRY_SPEC_OUTFLUX_NON_REACTIVE_RATE_DIST FOREIGN KEY (outflux_non_reactive_rate_distribution_id) REFERENCES FUN_RANDOM_DISTRIBUTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE AC_ARTIFICIAL_CHEMISTRY_SPEC ADD CONSTRAINT AC_ARTIFICIAL_CHEMISTRY_SPEC_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE AC_ARTIFICIAL_CHEMISTRY_SPEC_BOUND ADD CONSTRAINT AC_ARTIFICIAL_CHEMISTRY_SPEC_BOUND_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_AC_TASK ADD CONSTRAINT FK_EVO_AC_TASK_SPEC_BOUND FOREIGN KEY (spec_bound_id) REFERENCES AC_ARTIFICIAL_CHEMISTRY_SPEC_BOUND (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE EVO_AC_TASK ADD CONSTRAINT FK_EVO_AC_TASK_SIM_CONFIG FOREIGN KEY (sim_config_id) REFERENCES AC_SIMULATION_CONFIG (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE EVO_AC_TASK ADD CONSTRAINT FK_EVO_AC_TASK_ANALYSIS_SPEC FOREIGN KEY (multi_run_analysis_spec_id) REFERENCES DYN_MULTI_ANALYSIS_SPEC (id) ON UPDATE NO ACTION ON DELETE NO ACTION;


-- UM

ALTER TABLE UM_USER_ROLE_MAPPING ADD CONSTRAINT FK_UM_USER_ROLE_MAPPING_USER FOREIGN KEY (user_id) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE UM_USER_ROLE_MAPPING ADD CONSTRAINT FK_UM_USER_ROLE_MAPPING_ROLE FOREIGN KEY (role_id) REFERENCES UM_ROLE (id) ON UPDATE NO ACTION ON DELETE CASCADE;

-- EVO

ALTER TABLE EVO_GA_SETTING ADD CONSTRAINT FK_EVO_GA_SETTING_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_AC_TASK ADD CONSTRAINT FK_EVO_AC_TASK_GA_SET FOREIGN KEY (ga_setting_id) REFERENCES EVO_GA_SETTING (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE EVO_AC_TASK ADD CONSTRAINT FK_EVO_AC_TASK_GA_AC FOREIGN KEY (ac_id) REFERENCES AC_ARTIFICIAL_CHEMISTRY (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE EVO_AC_TASK ADD CONSTRAINT FK_EVO_AC_TASK_GA_EVALUATION FOREIGN KEY (ac_evaluation_id) REFERENCES AC_EVALUATION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE EVO_AC_TASK ADD CONSTRAINT FK_EVO_AC_TASK_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE EVO_AC_TASK ADD CONSTRAINT FK_EVO_AC_TASK_NETWORK FOREIGN KEY (network_id) REFERENCES NET_NETWORK (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_AC_TASK ADD CONSTRAINT FK_EVO_AC_TASK_NETWORK_EVALUATION FOREIGN KEY (network_evaluation_id) REFERENCES NET_EVALUATION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_AC_TASK_ACTION_SERIES_MAPPING ADD CONSTRAINT FK_EVO_AC_TASK_ACTION_SERIES_MAPPING_TASK FOREIGN KEY (evo_ac_task_id) REFERENCES EVO_AC_TASK (id) ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE EVO_AC_TASK_ACTION_SERIES_MAPPING ADD CONSTRAINT FK_EVO_AC_TASK_ACTION_SERIES_MAPPING_SERIES FOREIGN KEY (action_series_id) REFERENCES AC_ACTION_SERIES (id) ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE EVO_NET_TASK_ACTION_SERIES_MAPPING ADD CONSTRAINT FK_EVO_NET_TASK_ACTION_SERIES_MAPPING_TASK FOREIGN KEY (evo_task_id) REFERENCES EVO_AC_TASK (id) ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE EVO_NET_TASK_ACTION_SERIES_MAPPING ADD CONSTRAINT FK_EVO_NET_TASK_ACTION_SERIES_MAPPING_SERIES FOREIGN KEY (action_series_id) REFERENCES NET_ACTION_SERIES (id) ON UPDATE NO ACTION ON DELETE CASCADE;


ALTER TABLE EVO_RUN ADD CONSTRAINT FK_EVO_RUN_TASK FOREIGN KEY (evo_task_id) REFERENCES EVO_AC_TASK (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE EVO_RUN ADD CONSTRAINT FK_EVO_RUN_INIT_CHROM FOREIGN KEY (init_chromosome_id) REFERENCES EVO_CHROMOSOME (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE EVO_RUN ADD CONSTRAINT EVO_RUN_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_POPULATION ADD CONSTRAINT FK_EVO_POPULATION_RUN FOREIGN KEY (evo_run_id) REFERENCES EVO_RUN (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE EVO_POPULATION ADD CONSTRAINT FK_EVO_POPULATION_BEST_CHROMOSOME FOREIGN KEY (best_chromosome_id) REFERENCES EVO_CHROMOSOME (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE EVO_CHROMOSOME ADD CONSTRAINT FK_EVO_CHROMOSOME_POPULATION FOREIGN KEY (population_id) REFERENCES EVO_POPULATION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_AC_TASK_RATE_CONSTANT_TYPE_BOUND_MAPPING ADD CONSTRAINT FK_EVO_AC_TASK_RATE_CONSTANT_TYPE_BOUND_MAPPING_EVO_TASK FOREIGN KEY (evo_ac_task_id) REFERENCES EVO_AC_TASK (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE EVO_AC_TASK_RATE_CONSTANT_TYPE_BOUND_MAPPING ADD CONSTRAINT FK_EVO_AC_TASK_RATE_CONSTANT_TYPE_BOUND_MAPPING_RATE_CONST FOREIGN KEY (rate_constant_type_bound_id) REFERENCES AC_RATE_CONSTANT_TYPE_BOUND (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_AC_TASK_REACTION_MAPPING ADD CONSTRAINT FK_EVO_AC_TASK_REACTION_MAPPING_EVO_TASK FOREIGN KEY (evo_ac_task_id) REFERENCES EVO_AC_TASK (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_AC_TASK_REACTION_MAPPING ADD CONSTRAINT FK_EVO_AC_TASK_REACTION_MAPPING_REACTION FOREIGN KEY (reaction_id) REFERENCES AC_REACTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_AC_TASK_REACTION_GROUP_MAPPING ADD CONSTRAINT FK_EVO_AC_TASK_REACTION_GROUP_MAPPING_EVO_TASK FOREIGN KEY (evo_ac_task_id) REFERENCES EVO_AC_TASK (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_AC_TASK_REACTION_GROUP_MAPPING ADD CONSTRAINT FK_EVO_AC_TASK_REACTION_GROUP_MAPPING_REACTION_GROUP FOREIGN KEY (reaction_group_id) REFERENCES AC_REACTION_GROUP (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_AC_SPECIES_ASSIGNMENT_BOUND ADD CONSTRAINT FK_EVO_AC_SPECIES_ASSIGNMENT_BOUND_EVO_TASK FOREIGN KEY (evo_task_id) REFERENCES EVO_AC_TASK (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_BOUND ADD CONSTRAINT FK_EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_BOUND_EVO_TASK FOREIGN KEY (evo_task_id) REFERENCES EVO_AC_TASK (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_AC_SPECIES_ASSIGNMENT_MAPPING ADD CONSTRAINT FK_EVO_AC_SPECIES_ASSIGNMENT_MAPPING_BOUND FOREIGN KEY (evo_ac_species_bound_id) REFERENCES EVO_AC_SPECIES_ASSIGNMENT_BOUND (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_AC_SPECIES_ASSIGNMENT_MAPPING ADD CONSTRAINT FK_EVO_AC_SPECIES_ASSIGNMENT_MAPPING_ASSIGNMENT FOREIGN KEY (species_assignment_id) REFERENCES AC_SPECIES_ACTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_MAPPING ADD CONSTRAINT FK_EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_MAPPING_BOUND FOREIGN KEY (evo_ac_variable_bound_id) REFERENCES EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_BOUND (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_MAPPING ADD CONSTRAINT FK_EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_MAPPING_ASSIGNMENT FOREIGN KEY (variable_assignment_id) REFERENCES AC_CACHE_WRITE (id) ON UPDATE NO ACTION ON DELETE NO ACTION;


-- DYN
ALTER TABLE DYN_STATS ADD CONSTRAINT FK_DYN_STATS_SEQ FOREIGN KEY (seq_id) REFERENCES DYN_STATS_SEQ (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE DYN_MULTI_ANALYSIS_SPEC ADD CONSTRAINT FK_DYN_MULTI_ANALYSIS_SPEC_SINGLE_SPEC FOREIGN KEY (single_run_spec_id) REFERENCES DYN_SINGLE_ANALYSIS_SPEC (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DYN_MULTI_ANALYSIS_SPEC ADD CONSTRAINT FK_DYN_MULTI_ANALYSIS_SPEC_INIT_DIST FOREIGN KEY (initial_state_distribution_id) REFERENCES FUN_RANDOM_DISTRIBUTION (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE DYN_SINGLE_ANALYSIS_SPEC ADD CONSTRAINT DYN_SINGLE_ANALYSIS_SPEC_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE DYN_MULTI_ANALYSIS_SPEC ADD CONSTRAINT DYN_MULTI_ANALYSIS_SPEC_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE DYN_SINGLE_ANALYSIS_RESULT ADD CONSTRAINT FK_DYN_SINGLE_ANALYSIS_RESULT_SPAT_COR FOREIGN KEY (spatial_correlations_id) REFERENCES DYN_STATS_SEQ (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DYN_SINGLE_ANALYSIS_RESULT ADD CONSTRAINT FK_DYN_SINGLE_ANALYSIS_RESULT_TIME_COR FOREIGN KEY (time_correlations_id) REFERENCES DYN_STATS_SEQ (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DYN_SINGLE_ANALYSIS_RESULT ADD CONSTRAINT FK_DYN_SINGLE_ANALYSIS_RESULT_SPAT_STAT_POINT FOREIGN KEY (spatial_stationary_points_per_time_id) REFERENCES DYN_STATS_SEQ (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DYN_SINGLE_ANALYSIS_RESULT ADD CONSTRAINT FK_DYN_SINGLE_ANALYSIS_RESULT_TIME_STAT_POINT FOREIGN KEY (time_stationary_points_per_time_id) REFERENCES DYN_STATS_SEQ (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DYN_SINGLE_ANALYSIS_RESULT ADD CONSTRAINT FK_DYN_SINGLE_ANALYSIS_RESULT_SPAT_CUM_DIFF FOREIGN KEY (spatial_cumulative_diff_per_time_id) REFERENCES DYN_STATS_SEQ (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DYN_SINGLE_ANALYSIS_RESULT ADD CONSTRAINT FK_DYN_SINGLE_ANALYSIS_RESULT_TIME_CUM_DIFF FOREIGN KEY (time_cumulative_diff_per_time_id) REFERENCES DYN_STATS_SEQ (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DYN_SINGLE_ANALYSIS_RESULT ADD CONSTRAINT FK_DYN_SINGLE_ANALYSIS_RESULT_SPAT_NONLINE_ERRORS FOREIGN KEY (spatial_nonlinearity_errors_id) REFERENCES DYN_STATS_SEQ (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DYN_SINGLE_ANALYSIS_RESULT ADD CONSTRAINT FK_DYN_SINGLE_ANALYSIS_RESULT_TIME_NONLINE_ERRORS FOREIGN KEY (time_nonlinearity_errors_id) REFERENCES DYN_STATS_SEQ (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DYN_SINGLE_ANALYSIS_RESULT ADD CONSTRAINT FK_DYN_SINGLE_ANALYSIS_RESULT_DERRIDA FOREIGN KEY (derrida_results_id) REFERENCES DYN_STATS_SEQ (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DYN_SINGLE_ANALYSIS_RESULT ADD CONSTRAINT FK_DYN_SINGLE_ANALYSIS_RESULT_MULTI FOREIGN KEY (multi_run_result_id) REFERENCES DYN_MULTI_ANALYSIS_RESULT (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE DYN_SINGLE_ANALYSIS_RESULT ADD CONSTRAINT DYN_SINGLE_ANALYSIS_RESULT_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE DYN_MULTI_ANALYSIS_RESULT ADD CONSTRAINT FK_DYN_MULTI_ANALYSIS_RESULT_SPEC FOREIGN KEY (spec_id) REFERENCES DYN_MULTI_ANALYSIS_SPEC (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE DYN_MULTI_ANALYSIS_RESULT ADD CONSTRAINT FK_DYN_MULTI_ANALYSIS_RESULT_AC FOREIGN KEY (ac_id) REFERENCES AC_ARTIFICIAL_CHEMISTRY (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE DYN_MULTI_ANALYSIS_RESULT ADD CONSTRAINT DYN_MULTI_ANALYSIS_RESULT_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- TASK

ALTER TABLE TASK_EVO_RUN ADD CONSTRAINT FK_TASK_EVO_RUN_SUPER FOREIGN KEY (task_id) REFERENCES TASK (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE TASK_EVO_RUN ADD CONSTRAINT FK_TASK_EVO_RUN_EVO_TASK FOREIGN KEY (evo_task_id) REFERENCES EVO_AC_TASK (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE TASK ADD CONSTRAINT TASK_USER FOREIGN KEY (created_by) REFERENCES UM_USER (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

------------
-- INDECES
------------

-- FUN

CREATE INDEX ON FUN_FUNCTION (parent_id);

-- NET

CREATE INDEX ON NET_TOPOLOGY (created_by);
CREATE INDEX ON NET_LAYER_TOPOLOGY_MAPPING (parent_id);
CREATE INDEX ON NET_LAYER_TOPOLOGY_MAPPING (layer_id);
CREATE INDEX ON NET_TEMPLATE_TOPOLOGY (topology_id);
CREATE INDEX ON NET_SPATIAL_TOPOLOGY (topology_id);
CREATE INDEX ON NET_SPATIAL_TOPOLOGY (neighborhood_id);
CREATE INDEX ON NET_SPATIAL_NEIGHBORHOOD (created_by);
CREATE INDEX ON NET_SPATIAL_NEIGHBOR (parent_id);

CREATE INDEX ON NET_WEIGHT_SETTING (parent_id);
CREATE INDEX ON NET_WEIGHT_SETTING (created_by);
CREATE INDEX ON NET_WEIGHT_SETTING (random_distribution_id);

CREATE INDEX ON NET_FUNCTION (created_by);
CREATE INDEX ON NET_FUNCTION (parent_id);
CREATE INDEX ON NET_FUNCTION (function_id);

CREATE INDEX ON NET_NETWORK (topology_id);
CREATE INDEX ON NET_NETWORK (created_by);
CREATE INDEX ON NET_NETWORK (weight_setting_id);
CREATE INDEX ON NET_NETWORK (function_id);

CREATE INDEX ON NET_ACTION_SERIES (created_by);
CREATE INDEX ON NET_ACTION (action_series_id);
CREATE INDEX ON NET_ACTION (state_distribution_id);

CREATE INDEX ON NET_EVALUATION (evaluation_fun_id);
CREATE INDEX ON NET_EVALUATION (created_by);
CREATE INDEX ON NET_EVALUATION_ITEM (evaluation_id);
CREATE INDEX ON NET_EVALUATION_ITEM (evaluation_var_id);
CREATE INDEX ON NET_EVALUATION_ITEM (eval_fun_id);
CREATE INDEX ON NET_EVALUATION_VAR (evaluation_id);

CREATE INDEX ON NET_PERFORMANCE (created_by);
CREATE INDEX ON NET_PERFORMANCE (action_series_id);
CREATE INDEX ON NET_PERFORMANCE (network_id);
CREATE INDEX ON NET_PERFORMANCE (evaluation_id);
CREATE INDEX ON NET_PERFORMANCE (result_stats_id);
CREATE INDEX ON NET_PERFORMANCE (result_stats_seq_id);

CREATE INDEX ON NET_DERRIDA (created_by);
CREATE INDEX ON NET_DERRIDA (network_id);
CREATE INDEX ON NET_DERRIDA (result_stats_seq_id);

CREATE INDEX ON NET_DAMAGE_SPREADING (created_by);
CREATE INDEX ON NET_DAMAGE_SPREADING (network_id);
CREATE INDEX ON NET_DAMAGE_SPREADING (result_stats_seq_id);

-- AC

CREATE INDEX ON AC_ARTIFICIAL_CHEMISTRY (skin_compartment_id);
CREATE INDEX ON AC_ARTIFICIAL_CHEMISTRY (created_by);
CREATE INDEX ON AC_ARTIFICIAL_CHEMISTRY (generated_by_spec_id);
CREATE INDEX ON AC_ARTIFICIAL_CHEMISTRY (simulation_config_id);

CREATE INDEX ON AC_SPECIES (species_set_id);
CREATE INDEX ON AC_SPECIES_SET (created_by);
CREATE INDEX ON AC_SPECIES_SET (parent_set);

CREATE INDEX ON AC_PARAMETER (parameter_set_id);
CREATE INDEX ON AC_PARAMETER (evol_function_id);

CREATE INDEX ON AC_PARAMETER_SET (created_by);

CREATE INDEX ON AC_REACTION (reaction_set_id);
CREATE INDEX ON AC_REACTION (forward_rate_function_id);
CREATE INDEX ON AC_REACTION (reverse_rate_function_id);
CREATE INDEX ON AC_REACTION (reaction_group_id);

CREATE INDEX ON AC_REACTION_GROUP (reaction_set_id);

CREATE INDEX ON AC_SPECIES_REACTION_ASSOCIATION (species_id);
CREATE INDEX ON AC_SPECIES_REACTION_ASSOCIATION (reaction_id);

CREATE INDEX ON AC_REACTION_SET (species_set_id);
CREATE INDEX ON AC_REACTION_SET (created_by);

CREATE INDEX ON AC_COMPARTMENT (reaction_set_id);
CREATE INDEX ON AC_COMPARTMENT (created_by);

CREATE INDEX ON AC_SUB_COMPARTMENT_ASSOCIATION (parent_id);
CREATE INDEX ON AC_SUB_COMPARTMENT_ASSOCIATION (sub_id);

CREATE INDEX ON AC_COMPARTMENT_CHANNEL (compartment_id);
CREATE INDEX ON AC_COMPARTMENT_CHANNEL (source_species_id);
CREATE INDEX ON AC_COMPARTMENT_CHANNEL (target_species_id);

CREATE INDEX ON AC_COMPARTMENT_CHANNEL_GROUP (compartment_id);
CREATE INDEX ON AC_COMPARTMENT_CHANNEL_GROUP_MAPPING (group_id);
CREATE INDEX ON AC_COMPARTMENT_CHANNEL_GROUP_MAPPING (channel_id);

CREATE INDEX ON AC_SPECIES_ACTION (action_id);
CREATE INDEX ON AC_SPECIES_ACTION (species_id);
CREATE INDEX ON AC_SPECIES_ACTION (setting_fun_id);

CREATE INDEX ON AC_ACTION (action_series_id);

CREATE INDEX ON AC_ACTION_SERIES (species_set_id);
CREATE INDEX ON AC_ACTION_SERIES (created_by);
CREATE INDEX ON AC_ACTION_SERIES (parent_id);

CREATE INDEX ON AC_ACTION_SERIES_IMMUTABLE_SPECIES_MAPPING (action_series_id);
CREATE INDEX ON AC_ACTION_SERIES_IMMUTABLE_SPECIES_MAPPING (species_id);

CREATE INDEX ON AC_ACTION_VAR (action_series_id);
CREATE INDEX ON AC_CACHE_WRITE (action_id);
CREATE INDEX ON AC_CACHE_WRITE (variable_id);
CREATE INDEX ON AC_CACHE_WRITE (setting_fun_id);

CREATE INDEX ON AC_EVALUATED_SPECIES_ACTION (species_action_id);
CREATE INDEX ON AC_EVALUATED_SPECIES_ACTION (evaluated_action_id);
CREATE INDEX ON AC_EVALUATED_ACTION (action_id);
CREATE INDEX ON AC_EVALUATED_ACTION (evaluated_action_series_id);
CREATE INDEX ON AC_EVALUATED_ACTION_SERIES (action_series_id);
CREATE INDEX ON AC_EVALUATED_ACTION_SERIES (created_by);

CREATE INDEX ON AC_RUN (action_series_id);
CREATE INDEX ON AC_RUN (ac_id);
CREATE INDEX ON AC_RUN (created_by);
CREATE INDEX ON AC_RUN (evaluated_action_series_id);

CREATE INDEX ON AC_SPECIES_HISTORY (run_id);
CREATE INDEX ON AC_SPECIES_HISTORY (species_id);

CREATE INDEX ON AC_TRANSLATION_ITEM (translation_id);
CREATE INDEX ON AC_TRANSLATION_ITEM (translation_fun_id);
CREATE INDEX ON AC_TRANSLATION_ITEM (translation_var_id);

CREATE INDEX ON AC_RANGE_TRANSLATION (translation_series_id);

CREATE INDEX ON AC_TRANSLATION_SERIES (species_set_id);
CREATE INDEX ON AC_TRANSLATION_SERIES (created_by);

CREATE INDEX ON AC_TRANSLATED_RUN (translation_series_id);
CREATE INDEX ON AC_TRANSLATED_RUN (run_id);
CREATE INDEX ON AC_TRANSLATED_RUN (created_by);

CREATE INDEX ON AC_TRANSLATION_ITEM_HISTORY (translated_run_id);
CREATE INDEX ON AC_TRANSLATION_ITEM_HISTORY (translation_var_id);

CREATE INDEX ON AC_EVALUATION (created_by);
CREATE INDEX ON AC_EVALUATION (translation_series_id);
CREATE INDEX ON AC_EVALUATION (evaluation_fun_id);

CREATE INDEX ON AC_EVALUATED_RUN (evaluation_id);
CREATE INDEX ON AC_EVALUATED_RUN (translated_run_id);
CREATE INDEX ON AC_EVALUATED_RUN (created_by);

CREATE INDEX ON AC_TRANSLATION_VAR (translation_series_id);

CREATE INDEX ON AC_EVALUATED_PERFORMANCE (created_by);
CREATE INDEX ON AC_EVALUATED_PERFORMANCE (evaluation_id);
CREATE INDEX ON AC_EVALUATED_PERFORMANCE (compartment_id);
CREATE INDEX ON AC_EVALUATED_PERFORMANCE (simulation_config_id);
CREATE INDEX ON AC_EVALUATED_PERFORMANCE (action_series_id);

CREATE INDEX ON AC_PERFORMANCE_RATE_CONSTANT_TYPE_BOUND_MAPPING (random_rate_performance_id);
CREATE INDEX ON AC_PERFORMANCE_RATE_CONSTANT_TYPE_BOUND_MAPPING (rate_constant_type_bound_id);

CREATE INDEX ON AC_ARTIFICIAL_CHEMISTRY_SPEC (rate_constant_distribution_id);
CREATE INDEX ON AC_ARTIFICIAL_CHEMISTRY_SPEC (influx_rate_constant_distribution_id);
CREATE INDEX ON AC_ARTIFICIAL_CHEMISTRY_SPEC (outflux_rate_constant_distribution_id);
CREATE INDEX ON AC_ARTIFICIAL_CHEMISTRY_SPEC (upper_strand_partial_binding_distribution_id);
CREATE INDEX ON AC_ARTIFICIAL_CHEMISTRY_SPEC (outflux_non_reactive_rate_distribution_id);
CREATE INDEX ON AC_ARTIFICIAL_CHEMISTRY_SPEC (created_by);

CREATE INDEX ON AC_ARTIFICIAL_CHEMISTRY_SPEC_BOUND (created_by);

CREATE INDEX ON EVO_AC_TASK (spec_bound_id);
CREATE INDEX ON EVO_AC_TASK (sim_config_id);
CREATE INDEX ON EVO_AC_TASK (multi_run_analysis_spec_id);

CREATE INDEX ON AC_RATE_CONSTANT_TYPE_BOUND (created_by);

CREATE INDEX ON AC_SIMULATION_CONFIG (created_by);

-- UM

CREATE INDEX ON UM_USER_ROLE_MAPPING (user_id);
CREATE INDEX ON UM_USER_ROLE_MAPPING (role_id);

-- EVO

CREATE INDEX ON EVO_GA_SETTING (created_by);

CREATE INDEX ON EVO_AC_TASK (ga_setting_id);
CREATE INDEX ON EVO_AC_TASK (ac_id);
CREATE INDEX ON EVO_AC_TASK (ac_evaluation_id);
CREATE INDEX ON EVO_AC_TASK (created_by);

CREATE INDEX ON EVO_AC_TASK_ACTION_SERIES_MAPPING (evo_ac_task_id);
CREATE INDEX ON EVO_AC_TASK_ACTION_SERIES_MAPPING (action_series_id);

CREATE INDEX ON EVO_RUN (evo_task_id);
CREATE INDEX ON EVO_RUN (init_chromosome_id);
CREATE INDEX ON EVO_RUN (created_by);

CREATE INDEX ON EVO_POPULATION (evo_run_id);
CREATE INDEX ON EVO_POPULATION (best_chromosome_id);
CREATE INDEX ON EVO_CHROMOSOME (population_id);

CREATE INDEX ON EVO_AC_TASK_RATE_CONSTANT_TYPE_BOUND_MAPPING (evo_ac_task_id);
CREATE INDEX ON EVO_AC_TASK_RATE_CONSTANT_TYPE_BOUND_MAPPING (rate_constant_type_bound_id);

CREATE INDEX ON EVO_AC_TASK_REACTION_MAPPING (evo_ac_task_id);
CREATE INDEX ON EVO_AC_TASK_REACTION_MAPPING (reaction_id);
CREATE INDEX ON EVO_AC_TASK_REACTION_GROUP_MAPPING (evo_ac_task_id);
CREATE INDEX ON EVO_AC_TASK_REACTION_GROUP_MAPPING (reaction_group_id);

CREATE INDEX ON EVO_AC_TASK (network_id);

CREATE INDEX ON EVO_NET_TASK_ACTION_SERIES_MAPPING (evo_task_id);
CREATE INDEX ON EVO_NET_TASK_ACTION_SERIES_MAPPING (action_series_id);

CREATE INDEX ON EVO_AC_SPECIES_ASSIGNMENT_BOUND (evo_task_id);
CREATE INDEX ON EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_BOUND (evo_task_id);
CREATE INDEX ON EVO_AC_SPECIES_ASSIGNMENT_MAPPING (evo_ac_species_bound_id);
CREATE INDEX ON EVO_AC_SPECIES_ASSIGNMENT_MAPPING (species_assignment_id);
CREATE INDEX ON EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_MAPPING (evo_ac_variable_bound_id);
CREATE INDEX ON EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_MAPPING (variable_assignment_id);


-- DYN
CREATE INDEX ON DYN_STATS (seq_id);

CREATE INDEX ON DYN_SINGLE_ANALYSIS_SPEC (created_by);

CREATE INDEX ON DYN_MULTI_ANALYSIS_SPEC (single_run_spec_id);
CREATE INDEX ON DYN_MULTI_ANALYSIS_SPEC (initial_state_distribution_id);

CREATE INDEX ON DYN_MULTI_ANALYSIS_SPEC (created_by);

CREATE INDEX ON DYN_SINGLE_ANALYSIS_RESULT (spatial_correlations_id);
CREATE INDEX ON DYN_SINGLE_ANALYSIS_RESULT (time_correlations_id);
CREATE INDEX ON DYN_SINGLE_ANALYSIS_RESULT (spatial_stationary_points_per_time_id);
CREATE INDEX ON DYN_SINGLE_ANALYSIS_RESULT (time_stationary_points_per_time_id);
CREATE INDEX ON DYN_SINGLE_ANALYSIS_RESULT (spatial_cumulative_diff_per_time_id);
CREATE INDEX ON DYN_SINGLE_ANALYSIS_RESULT (time_cumulative_diff_per_time_id);
CREATE INDEX ON DYN_SINGLE_ANALYSIS_RESULT (spatial_nonlinearity_errors_id);

CREATE INDEX ON DYN_SINGLE_ANALYSIS_RESULT (time_nonlinearity_errors_id);
CREATE INDEX ON DYN_SINGLE_ANALYSIS_RESULT (derrida_results_id);
CREATE INDEX ON DYN_SINGLE_ANALYSIS_RESULT (multi_run_result_id);
CREATE INDEX ON DYN_SINGLE_ANALYSIS_RESULT (created_by);
CREATE INDEX ON DYN_MULTI_ANALYSIS_RESULT (spec_id);
CREATE INDEX ON DYN_MULTI_ANALYSIS_RESULT (ac_id);
CREATE INDEX ON DYN_MULTI_ANALYSIS_RESULT (created_by);

-- TASK

CREATE INDEX ON TASK_EVO_RUN (task_id);
CREATE INDEX ON TASK_EVO_RUN (evo_task_id);
CREATE INDEX ON TASK (created_by);

------------
-- SEQUENCE
------------

-- FUN

CREATE SEQUENCE FUN_FUNCTION_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE FUN_FUNCTION ALTER COLUMN id SET DEFAULT nextval('FUN_FUNCTION_ID_SEQ'::regclass);

CREATE SEQUENCE FUN_RANDOM_DISTRIBUTION_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE FUN_RANDOM_DISTRIBUTION ALTER COLUMN id SET DEFAULT nextval('FUN_RANDOM_DISTRIBUTION_ID_SEQ'::regclass);

-- NET

CREATE SEQUENCE NET_TOPOLOGY_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE NET_TOPOLOGY ALTER COLUMN id SET DEFAULT nextval('NET_TOPOLOGY_ID_SEQ'::regclass);

CREATE SEQUENCE NET_SPATIAL_NEIGHBORHOOD_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE NET_SPATIAL_NEIGHBORHOOD ALTER COLUMN id SET DEFAULT nextval('NET_SPATIAL_NEIGHBORHOOD_ID_SEQ'::regclass);

CREATE SEQUENCE NET_SPATIAL_NEIGHBOR_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE NET_SPATIAL_NEIGHBOR ALTER COLUMN id SET DEFAULT nextval('NET_SPATIAL_NEIGHBOR_ID_SEQ'::regclass);

CREATE SEQUENCE NET_WEIGHT_SETTING_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE NET_WEIGHT_SETTING ALTER COLUMN id SET DEFAULT nextval('NET_WEIGHT_SETTING_ID_SEQ'::regclass);

CREATE SEQUENCE NET_FUNCTION_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE NET_FUNCTION ALTER COLUMN id SET DEFAULT nextval('NET_FUNCTION_ID_SEQ'::regclass);

CREATE SEQUENCE NET_NETWORK_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE NET_NETWORK ALTER COLUMN id SET DEFAULT nextval('NET_NETWORK_ID_SEQ'::regclass);

CREATE SEQUENCE NET_ACTION_SERIES_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE NET_ACTION_SERIES ALTER COLUMN id SET DEFAULT nextval('NET_ACTION_SERIES_ID_SEQ'::regclass);

CREATE SEQUENCE NET_ACTION_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE NET_ACTION ALTER COLUMN id SET DEFAULT nextval('NET_ACTION_ID_SEQ'::regclass);

CREATE SEQUENCE NET_EVALUATION_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE NET_EVALUATION ALTER COLUMN id SET DEFAULT nextval('NET_EVALUATION_ID_SEQ'::regclass);

CREATE SEQUENCE NET_PERFORMANCE_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE NET_PERFORMANCE ALTER COLUMN id SET DEFAULT nextval('NET_PERFORMANCE_ID_SEQ'::regclass);

CREATE SEQUENCE NET_EVALUATION_ITEM_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE NET_EVALUATION_ITEM ALTER COLUMN id SET DEFAULT nextval('NET_EVALUATION_ITEM_ID_SEQ'::regclass);

CREATE SEQUENCE NET_EVALUATION_VAR_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE NET_EVALUATION_VAR ALTER COLUMN id SET DEFAULT nextval('NET_EVALUATION_VAR_ID_SEQ'::regclass);

CREATE SEQUENCE NET_DERRIDA_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE NET_DERRIDA ALTER COLUMN id SET DEFAULT nextval('NET_DERRIDA_ID_SEQ'::regclass);

CREATE SEQUENCE NET_DAMAGE_SPREADING_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE NET_DAMAGE_SPREADING ALTER COLUMN id SET DEFAULT nextval('NET_DAMAGE_SPREADING_ID_SEQ'::regclass);

-- AC

CREATE SEQUENCE AC_ARTIFICIAL_CHEMISTRY_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_ARTIFICIAL_CHEMISTRY ALTER COLUMN id SET DEFAULT nextval('AC_ARTIFICIAL_CHEMISTRY_ID_SEQ'::regclass);

CREATE SEQUENCE AC_SPECIES_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_SPECIES ALTER COLUMN id SET DEFAULT nextval('AC_SPECIES_ID_SEQ'::regclass);

CREATE SEQUENCE AC_SPECIES_SET_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_SPECIES_SET ALTER COLUMN id SET DEFAULT nextval('AC_SPECIES_SET_ID_SEQ'::regclass);

CREATE SEQUENCE AC_PARAMETER_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_PARAMETER ALTER COLUMN id SET DEFAULT nextval('AC_PARAMETER_ID_SEQ'::regclass);

CREATE SEQUENCE AC_REACTION_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_REACTION ALTER COLUMN id SET DEFAULT nextval('AC_REACTION_ID_SEQ'::regclass);

CREATE SEQUENCE AC_SPECIES_REACTION_ASSOCIATION_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_SPECIES_REACTION_ASSOCIATION ALTER COLUMN id SET DEFAULT nextval('AC_SPECIES_REACTION_ASSOCIATION_ID_SEQ'::regclass);

CREATE SEQUENCE AC_REACTION_SET_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_REACTION_SET ALTER COLUMN id SET DEFAULT nextval('AC_REACTION_SET_ID_SEQ'::regclass);

CREATE SEQUENCE AC_REACTION_GROUP_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_REACTION_GROUP ALTER COLUMN id SET DEFAULT nextval('AC_REACTION_GROUP_ID_SEQ'::regclass);

CREATE SEQUENCE AC_COMPARTMENT_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_COMPARTMENT ALTER COLUMN id SET DEFAULT nextval('AC_COMPARTMENT_ID_SEQ'::regclass);

CREATE SEQUENCE AC_SUB_COMPARTMENT_ASSOCIATION_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_SUB_COMPARTMENT_ASSOCIATION ALTER COLUMN id SET DEFAULT nextval('AC_SUB_COMPARTMENT_ASSOCIATION_ID_SEQ'::regclass);

CREATE SEQUENCE AC_COMPARTMENT_CHANNEL_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_COMPARTMENT_CHANNEL ALTER COLUMN id SET DEFAULT nextval('AC_COMPARTMENT_CHANNEL_ID_SEQ'::regclass);

CREATE SEQUENCE AC_COMPARTMENT_CHANNEL_GROUP_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_COMPARTMENT_CHANNEL_GROUP ALTER COLUMN id SET DEFAULT nextval('AC_COMPARTMENT_CHANNEL_GROUP_ID_SEQ'::regclass);

CREATE SEQUENCE AC_SPECIES_ACTION_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_SPECIES_ACTION ALTER COLUMN id SET DEFAULT nextval('AC_SPECIES_ACTION_ID_SEQ'::regclass);

CREATE SEQUENCE AC_ACTION_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_ACTION ALTER COLUMN id SET DEFAULT nextval('AC_ACTION_ID_SEQ'::regclass);

CREATE SEQUENCE AC_ACTION_SERIES_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_ACTION_SERIES ALTER COLUMN id SET DEFAULT nextval('AC_ACTION_SERIES_ID_SEQ'::regclass);

CREATE SEQUENCE AC_ACTION_VAR_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_ACTION_VAR ALTER COLUMN id SET DEFAULT nextval('AC_ACTION_VAR_ID_SEQ'::regclass);

CREATE SEQUENCE AC_CACHE_WRITE_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_CACHE_WRITE ALTER COLUMN id SET DEFAULT nextval('AC_CACHE_WRITE_ID_SEQ'::regclass);

CREATE SEQUENCE AC_EVALUATED_SPECIES_ACTION_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_EVALUATED_SPECIES_ACTION ALTER COLUMN id SET DEFAULT nextval('AC_EVALUATED_SPECIES_ACTION_ID_SEQ'::regclass);

CREATE SEQUENCE AC_EVALUATED_ACTION_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_EVALUATED_ACTION ALTER COLUMN id SET DEFAULT nextval('AC_EVALUATED_ACTION_ID_SEQ'::regclass);

CREATE SEQUENCE AC_EVALUATED_ACTION_SERIES_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_EVALUATED_ACTION_SERIES ALTER COLUMN id SET DEFAULT nextval('AC_EVALUATED_ACTION_SERIES_ID_SEQ'::regclass);

CREATE SEQUENCE AC_RUN_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_RUN ALTER COLUMN id SET DEFAULT nextval('AC_RUN_ID_SEQ'::regclass);

CREATE SEQUENCE AC_SPECIES_HISTORY_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_SPECIES_HISTORY ALTER COLUMN id SET DEFAULT nextval('AC_SPECIES_HISTORY_ID_SEQ'::regclass);

CREATE SEQUENCE AC_TRANSLATION_ITEM_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_TRANSLATION_ITEM ALTER COLUMN id SET DEFAULT nextval('AC_TRANSLATION_ITEM_ID_SEQ'::regclass);

CREATE SEQUENCE AC_RANGE_TRANSLATION_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_RANGE_TRANSLATION ALTER COLUMN id SET DEFAULT nextval('AC_RANGE_TRANSLATION_ID_SEQ'::regclass);

CREATE SEQUENCE AC_TRANSLATION_SERIES_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_TRANSLATION_SERIES ALTER COLUMN id SET DEFAULT nextval('AC_TRANSLATION_SERIES_ID_SEQ'::regclass);

CREATE SEQUENCE AC_TRANSLATED_RUN_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_TRANSLATED_RUN ALTER COLUMN id SET DEFAULT nextval('AC_TRANSLATED_RUN_ID_SEQ'::regclass);

CREATE SEQUENCE AC_TRANSLATION_ITEM_HISTORY_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_TRANSLATION_ITEM_HISTORY ALTER COLUMN id SET DEFAULT nextval('AC_TRANSLATION_ITEM_HISTORY_ID_SEQ'::regclass);

CREATE SEQUENCE AC_TRANSLATION_VAR_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_TRANSLATION_VAR ALTER COLUMN id SET DEFAULT nextval('AC_TRANSLATION_VAR_ID_SEQ'::regclass);

CREATE SEQUENCE AC_EVALUATION_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_EVALUATION ALTER COLUMN id SET DEFAULT nextval('AC_EVALUATION_ID_SEQ'::regclass);

CREATE SEQUENCE AC_EVALUATED_RUN_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_EVALUATED_RUN ALTER COLUMN id SET DEFAULT nextval('AC_EVALUATED_RUN_ID_SEQ'::regclass);

CREATE SEQUENCE AC_EVALUATED_PERFORMANCE_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_EVALUATED_PERFORMANCE ALTER COLUMN id SET DEFAULT nextval('AC_EVALUATED_PERFORMANCE_ID_SEQ'::regclass);

CREATE SEQUENCE AC_ARTIFICIAL_CHEMISTRY_SPEC_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_ARTIFICIAL_CHEMISTRY_SPEC ALTER COLUMN id SET DEFAULT nextval('AC_ARTIFICIAL_CHEMISTRY_SPEC_ID_SEQ'::regclass);

CREATE SEQUENCE AC_ARTIFICIAL_CHEMISTRY_SPEC_BOUND_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_ARTIFICIAL_CHEMISTRY_SPEC_BOUND ALTER COLUMN id SET DEFAULT nextval('AC_ARTIFICIAL_CHEMISTRY_SPEC_BOUND_ID_SEQ'::regclass);

-- UM

CREATE SEQUENCE UM_USER_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE UM_USER ALTER COLUMN id SET DEFAULT nextval('UM_USER_ID_SEQ'::regclass);

CREATE SEQUENCE UM_ROLE_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE UM_ROLE ALTER COLUMN id SET DEFAULT nextval('UM_ROLE_ID_SEQ'::regclass);

CREATE SEQUENCE AC_RATE_CONSTANT_TYPE_BOUND_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_RATE_CONSTANT_TYPE_BOUND ALTER COLUMN id SET DEFAULT nextval('AC_RATE_CONSTANT_TYPE_BOUND_ID_SEQ'::regclass);

CREATE SEQUENCE AC_SIMULATION_CONFIG_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE AC_SIMULATION_CONFIG ALTER COLUMN id SET DEFAULT nextval('AC_SIMULATION_CONFIG_ID_SEQ'::regclass);

-- EVO

CREATE SEQUENCE EVO_GA_SETTING_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE EVO_GA_SETTING ALTER COLUMN id SET DEFAULT nextval('EVO_GA_SETTING_ID_SEQ'::regclass);

CREATE SEQUENCE EVO_AC_TASK_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE EVO_AC_TASK ALTER COLUMN id SET DEFAULT nextval('EVO_AC_TASK_ID_SEQ'::regclass);

CREATE SEQUENCE EVO_AC_TASK_ACTION_SERIES_MAPPING_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE EVO_AC_TASK_ACTION_SERIES_MAPPING ALTER COLUMN id SET DEFAULT nextval('EVO_AC_TASK_ACTION_SERIES_MAPPING_ID_SEQ'::regclass);

CREATE SEQUENCE EVO_CHROMOSOME_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE EVO_CHROMOSOME ALTER COLUMN id SET DEFAULT nextval('EVO_CHROMOSOME_ID_SEQ'::regclass);

CREATE SEQUENCE EVO_POPULATION_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE EVO_POPULATION ALTER COLUMN id SET DEFAULT nextval('EVO_POPULATION_ID_SEQ'::regclass);

CREATE SEQUENCE EVO_RUN_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE EVO_RUN ALTER COLUMN id SET DEFAULT nextval('EVO_RUN_ID_SEQ'::regclass);

CREATE SEQUENCE EVO_AC_SPECIES_ASSIGNMENT_BOUND_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE EVO_AC_SPECIES_ASSIGNMENT_BOUND ALTER COLUMN id SET DEFAULT nextval('EVO_AC_SPECIES_ASSIGNMENT_BOUND_ID_SEQ'::regclass);

CREATE SEQUENCE EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_BOUND_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_BOUND ALTER COLUMN id SET DEFAULT nextval('EVO_AC_INTERACTION_VARIABLE_ASSIGNMENT_BOUND_ID_SEQ'::regclass);

-- DYN

CREATE SEQUENCE DYN_STATS_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE DYN_STATS ALTER COLUMN id SET DEFAULT nextval('DYN_STATS_ID_SEQ'::regclass);

CREATE SEQUENCE DYN_STATS_SEQ_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE DYN_STATS_SEQ ALTER COLUMN id SET DEFAULT nextval('DYN_STATS_SEQ_ID_SEQ'::regclass);

CREATE SEQUENCE DYN_SINGLE_ANALYSIS_SPEC_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE DYN_SINGLE_ANALYSIS_SPEC ALTER COLUMN id SET DEFAULT nextval('DYN_SINGLE_ANALYSIS_SPEC_ID_SEQ'::regclass);

CREATE SEQUENCE DYN_MULTI_ANALYSIS_SPEC_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE DYN_MULTI_ANALYSIS_SPEC ALTER COLUMN id SET DEFAULT nextval('DYN_MULTI_ANALYSIS_SPEC_ID_SEQ'::regclass);

CREATE SEQUENCE DYN_SINGLE_ANALYSIS_RESULT_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE DYN_SINGLE_ANALYSIS_RESULT ALTER COLUMN id SET DEFAULT nextval('DYN_SINGLE_ANALYSIS_RESULT_ID_SEQ'::regclass);

CREATE SEQUENCE DYN_MULTI_ANALYSIS_RESULT_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE DYN_MULTI_ANALYSIS_RESULT ALTER COLUMN id SET DEFAULT nextval('DYN_MULTI_ANALYSIS_RESULT_ID_SEQ'::regclass);

-- TASK

CREATE SEQUENCE TASK_ID_SEQ
  INCREMENT 1
  MINVALUE 1000
  MAXVALUE 9223372036854775807
  START 1000
  CACHE 1;
ALTER TABLE TASK ALTER COLUMN id SET DEFAULT nextval('TASK_ID_SEQ'::regclass);
