\set _USER coeladmin
\set _PASSWORD '\'changeme\''
\set _TABLESPACE pg_default
\set _DATABASE coel
\set _SCHEMA coel_schema

CREATE USER :_USER WITH PASSWORD :_PASSWORD CREATEDB CREATEUSER;
CREATE DATABASE :_DATABASE OWNER :_USER ENCODING 'UNICODE' TABLESPACE :_TABLESPACE;
CREATE SCHEMA :_SCHEMA AUTHORIZATION :_USER;
GRANT ALL ON SCHEMA :_SCHEMA TO :_USER;
