-- FUN

DELETE FROM FUN_TRANSITION_TABLE;

DELETE FROM FUN_EXPRESSION;

DELETE FROM FUN_FUNCTION;

DELETE FROM FUN_RANDOM_DISTRIBUTION;

-- NET

DELETE FROM NET_DAMAGE_SPREADING;

DELETE FROM NET_DERRIDA;

DELETE FROM NET_NETWORK;

DELETE FROM NET_WEIGHT_SETTING;

DELETE FROM NET_TEMPLATE_TOPOLOGY;

DELETE FROM NET_SPATIAL_TOPOLOGY;

DELETE FROM NET_SPATIAL_NEIGHBOR;

DELETE FROM NET_SPATIAL_NEIGHBORHOOD;

DELETE FROM NET_LAYER_TOPOLOGY_MAPPING;

DELETE FROM NET_TOPOLOGY;

DELETE FROM NET_FUNCTION;

DELETE FROM NET_ACTION;

DELETE FROM NET_ACTION_SERIES;

-- EVO

DELETE FROM EVO_AC_TASK_RATE_CONSTANT_TYPE_BOUND_MAPPING;

DELETE FROM EVO_AC_TASK_REACTION_MAPPING;

DELETE FROM EVO_AC_TASK_REACTION_GROUP_MAPPING;

DELETE FROM EVO_CHROMOSOME;

DELETE FROM EVO_POPULATION;

DELETE FROM EVO_RUN;

DELETE FROM EVO_AC_TASK_ACTION_SERIES_MAPPING;

DELETE FROM EVO_NET_TASK_ACTION_SERIES_MAPPING;

DELETE FROM EVO_AC_TASK;

DELETE FROM EVO_GA_SETTING;

-- AC

DELETE FROM AC_PERFORMANCE_RATE_CONSTANT_TYPE_BOUND_MAPPING;

DELETE FROM AC_EVALUATED_PERFORMANCE;

DELETE FROM AC_EVALUATED_RUN;

DELETE FROM AC_EVALUATION;

DELETE FROM AC_TRANSLATION_ITEM_HISTORY;

DELETE FROM AC_TRANSLATED_RUN;

DELETE FROM AC_SPECIES_HISTORY;

DELETE FROM AC_EVALUATED_SPECIES_ACTION;

DELETE FROM AC_EVALUATED_ACTION;

DELETE FROM AC_EVALUATED_ACTION_SERIES;

DELETE FROM AC_RUN;

DELETE FROM AC_SPECIES_ACTION;

DELETE FROM AC_CACHE_WRITE;

DELETE FROM AC_ACTION_VAR;

DELETE FROM AC_ACTION;

DELETE FROM AC_ACTION_SERIES;

DELETE FROM AC_TRANSLATION_ITEM;

DELETE FROM AC_TRANSLATION_VAR;

DELETE FROM AC_RANGE_TRANSLATION;

DELETE FROM AC_TRANSLATION_SERIES;

DELETE FROM AC_ARTIFICIAL_CHEMISTRY;

DELETE FROM AC_COMPARTMENT_CHANNEL_GROUP_MAPPING;

DELETE FROM AC_COMPARTMENT_CHANNEL_GROUP;

DELETE FROM AC_COMPARTMENT_CHANNEL;

DELETE FROM AC_SUB_COMPARTMENT_ASSOCIATION;

DELETE FROM AC_COMPARTMENT;

DELETE FROM AC_SPECIES_REACTION_ASSOCIATION;

DELETE FROM AC_REACTION;

DELETE FROM AC_REACTION_SET;

DELETE FROM AC_REACTION_GROUP;

DELETE FROM AC_SPECIES;

DELETE FROM AC_SPECIES_SET;

DELETE FROM AC_PARAMETER;

DELETE FROM AC_PARAMETER_SET;

DELETE FROM AC_RATE_CONSTANT_TYPE_BOUND;

DELETE FROM AC_ARTIFICIAL_CHEMISTRY_SPEC;

DELETE FROM AC_SIMULATION_CONFIG;

-- UM

DELETE FROM UM_USER_ROLE_MAPPING;

DELETE FROM UM_USER;

DELETE FROM UM_ROLE;

-- DYN

DELETE FROM DYN_STATS_SEQ;

DELETE FROM DYN_STATS;

DELETE FROM DYN_SINGLE_ANALYSIS_SPEC;

DELETE FROM DYN_MULTI_ANALYSIS_SPEC;

DELETE FROM DYN_MULTI_ANALYSIS_RESULT;

DELETE FROM DYN_SINGLE_ANALYSIS_RESULT;

-- TASK

DELETE FROM TASK;

DELETE FROM TASK_EVO_RUN;
